/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kruwell.program;

/**
 *
 * @author Sitti Halima
 */
public class Karyawan extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        txtNIP.setEditable(true);
    }

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        txtNIP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cbGolongan = new javax.swing.JComboBox<>();
        txtJam = new javax.swing.JTextField();
        txtGaji = new javax.swing.JTextField();
        txtTunjangan = new javax.swing.JTextField();
        txtGajiBersih = new javax.swing.JTextField();
        tbTambah = new javax.swing.JButton();
        tbSimpan = new javax.swing.JButton();
        tbEdit = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        tbKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DATA KARYAWAN CV.XXI");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 0, -1, -1));

        jLabel2.setText("NIP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 49, -1, -1));

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 87, -1, -1));

        jLabel3.setText("Golongan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 125, -1, -1));

        jLabel4.setText("Jam_Lembur");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 49, -1, -1));

        jLabel5.setText("Gaji Pokok");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 87, -1, -1));

        jLabel6.setText("Tunjangan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 125, -1, -1));

        jLabel7.setText("Gaji Bersih");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 163, -1, -1));

        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 237, -1, 267));
        getContentPane().add(txtNIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 46, 114, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 84, 169, -1));

        cbGolongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        getContentPane().add(cbGolongan, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 122, -1, -1));
        getContentPane().add(txtJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 46, 62, -1));

        txtGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajiActionPerformed(evt);
            }
        });
        getContentPane().add(txtGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 84, 62, -1));

        txtTunjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTunjanganActionPerformed(evt);
            }
        });
        getContentPane().add(txtTunjangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 122, 62, -1));

        txtGajiBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajiBersihActionPerformed(evt);
            }
        });
        getContentPane().add(txtGajiBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 160, 62, -1));

        tbTambah.setText("Tambah Data");
        getContentPane().add(tbTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, -1, -1));

        tbSimpan.setText("Simpan");
        getContentPane().add(tbSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 208, -1, -1));

        tbEdit.setText("Edit");
        getContentPane().add(tbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 208, -1, -1));

        tbHapus.setText("Hapus");
        getContentPane().add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 208, -1, -1));

        tbKeluar.setText("Keluar");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tbKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 208, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGajiActionPerformed

    private void txtTunjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTunjanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTunjanganActionPerformed

    private void txtGajiBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajiBersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGajiBersihActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_tbKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGolongan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKaryawan;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JButton tbSimpan;
    private javax.swing.JButton tbTambah;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtGajiBersih;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTunjangan;
    // End of variables declaration//GEN-END:variables
}
